# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b87bc9fb559c7d12b574c92bdd335a0a58a5a5aa18f7dbea87d07e87e91060774b5a7d005dc2a50b0e2db8f4e7c6a7b4f88ada934752210034908ed9984a79ab

test:
  secret_key_base: 18dff4d79eecfcdc3b2279ce0dd9c849f263548d34c25536738dc5342906a0bb53d05293d60843c4e734d0a84c65208bc7abf6406a59517086338832c1d4b18d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
